MovieBoxProject/MovieBox/urls.py
from django.conf.urls import url
from MovieBox import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^$', views.FrontPageMovieListView.as_view(), name = 'home'),
    url(r'^actor/add/$', views.ActorCreateView.as_view(), name='actor_create'),
    url(r'^actor/(?P<pk>[0-9]+)/$', views.ActorDetailView.as_view(), name='actor_detail'),
    url(r'^movie/(?P<pk>[0-9]+)/$', views.MovieDetailView.as_view(), name = 'movie_detail'),
    url(r'^movie/(?P<pk>[0-9]+)/delete$',  views.MovieDeleteView.as_view(), name='movie_delete'),
    url(r'^movie/add/$', views.MovieCreateView.as_view(), name='movie_create'),
    url(r'^movie/(?P<pk>[0-9]+)/update$', views.MovieUpdateView.as_view(), name='movie_update'),
    url(r'^movie/(?P<pk>[0-9]+)/voted/(?P<value>[0-5])/$', views.AddedScoreView.as_view(), name='voted'),
    url(r'^movie/(?P<pk>[0-9]+)/favorite/(?P<value>[0-9]+)/$', views.AddedFavoriteView.as_view(), name='favorite'),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^search/(?P<input>[A-Za-z]+)/$', views.SearchPageListView.as_view(), name="search"),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.UserProfileDetailView.as_view(), name='profile'),
    url(r'^movie/(?P<pk>[0-9]+)/voted/(?P<value>[0-5])/$', views.AddedScoreView.as_view(), name="voted"),
    url(r'^register/$', views.UserCreateView.as_view(), name="register"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MovieBoxProject/MovieBoxProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('MovieBox.urls')),
]

MovieBoxProject/MovieBox/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

# Create your models here.


class Actor(models.Model):
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField(null=True, blank=True)
    picture =  models.ImageField(default='', blank=True)

    def __str__(self):
        return self.last_name + " " + self.first_name


class Movie(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField()
    genre = models.IntegerField(choices=[
        (1, "Comedy"),
        (2, "Action"),
        (3, "Thriller"),
        (4, "Drama"),
        (5, "Horror"),
        (6, "Romance"),
        (7, "Fantasy"),
        (8, "Sci-Fi"),
    ])
    score = models.FloatField(default=0.0)
    cover =  models.ImageField(default='', blank=True)
    description = models.TextField(max_length=5000)
    actors = models.ManyToManyField(Actor, related_name='Movies')

    # verifica daca un user a votat pentru filmul respectiv
    votes = models.ManyToManyField(User, blank=True, related_name='UserMovie')


    def __str__(self):
        return self.name


class MBUserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='mbuserprofile')
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    birth_date =  models.DateField(null=True, blank=True)
    profile_pic = models.ImageField(upload_to = 'images/', null=True, blank=True)
    favourites = models.ManyToManyField(Movie, related_name='Favourites')

    def __str__(self):
        return self.first_name + " " + self.last_name

MovieBoxProject/MovieBox/forms.py
from django import forms
from MovieBox.models import Movie
from MovieBox.models import Actor, MBUserProfile
from django.contrib.auth.models import User

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'date', 'genre', 'actors', 'description', 'cover')

class ActorForm(forms.ModelForm):
    class Meta:
        model = Actor
        fields = ('first_name', 'last_name', 'birth_date', 'picture')

class LoginForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

class SignUpForm(forms.ModelForm):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = MBUserProfile
        fields = [
            'first_name', 'last_name', 'birth_date',
            'profile_pic'
        ]

    def save(self, commit=True):
        instance = super(SignUpForm, self).save(commit=False)
        user = User(username=self.data['email'], password=self.data['password'])
        user.save()
        instance.user = user
        instance.save()
        return instance

MovieBoxProject/MovieBox/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from MovieBox.models import Movie, Actor, MBUserProfile
from MovieBox.forms import MovieForm, LoginForm, ActorForm, SignUpForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseForbidden

# Create your views here.

class FrontPageMovieListView(ListView):
    template_name = 'homeMovieList.html'
    model = Movie
    context_object_name = 'movies'


class MovieDetailView(DetailView):
    template_name = 'movie.html'
    model = Movie
    context_object_name = 'movie'


class ActorDetailView(DetailView):
    template_name = 'actor.html'
    model = Actor
    context_object_name = 'actor'


class MovieDeleteView(DeleteView):
    template_name = 'delete.html'
    model = Movie


class MovieCreateView(CreateView):
    template_name = 'add_movie.html'
    form_class = MovieForm
    model = Movie

    def get_success_url(self, *args, **kwargs):
        return reverse('movie_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(MovieCreateView, self).get_context_data(**kwargs)
        context['actors'] = Actor.objects.all()
        return context

class MovieUpdateView(UpdateView):
    template_name = 'edit_movie.html'
    form_class = MovieForm
    model = Movie

    def get_success_url(self, *args, **kwargs):
        return reverse('movie_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(MovieUpdateView, self).get_context_data(**kwargs)
        actors = Actor.objects.all()
        for actor in actors:
            actor.movies_pk = [pk for pk in actor.Movies.values_list('pk', flat=True)]
        context['actors'] = actors
        context['movie_pk'] = self.object.pk
        return context

class UserProfileDetailView(DetailView):
    template_name = 'profile.html'
    model = MBUserProfile
    context_object_name = 'mbuserprofile'

class ActorCreateView(CreateView):
    template_name = 'add_actor.html'
    form_class = ActorForm
    model = Actor

    def get_success_url(self, *args, **kwargs):
        return reverse('actor_detail', kwargs={'pk': self.object.pk})

class UserCreateView(CreateView):
    template_name = "signup.html"
    form_class = SignUpForm
    model = MBUserProfile

    def get_success_url(self, *args, **kwargs):
        return reverse('home')

#afisare mesaj de eroare daca username-ul sau parola nu sunt valide
def login_view(request):
    context = {}
    if request.method == 'GET':
        form = LoginForm()
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            if user:
                login(request=request,
                      user=user)
                return redirect('home')
            else:
                context['error_message'] = 'Wrong username or password!'
    context['form'] = form
    return render(request, 'login.html', context)


def logout_view(request):
    if request.method == 'GET':
        logout(request)
        return redirect('login')

class SearchPageListView(ListView):
    template_name = 'search.html'
    model = Movie
    context_object_name = 'items'
    def get_queryset(self):
        searchInput = self.kwargs['input']
        queryset = Movie.objects.filter(name__contains=searchInput).all()
        return queryset

class AddedScoreView(View):
     def get(self, request, *args, **kwargs):
        obj = Movie.objects.get(pk=kwargs['pk'])
        votedScore = float(kwargs['value'])
        if request.user not in obj.votes.all():
            nr = int(obj.votes.count())
            obj.score = str(format((float(obj.score) * nr + votedScore) / (nr + 1), '.2f'))
            obj.votes.add(request.user)
            obj.save()
            return render( request, 'voted.html', {'response': 'Thank you for your vote!'})
        else:
            return render( request, 'voted.html', {'response': 'You gave already voted for this movie'})

def upload_pic(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            m = Movie.objects.get(pk=request.Movie.pk)
            m.cover = form.cleaned_data['cover']
            m.save()
            return HttpResponse('image upload success')
    return HttpResponseForbidden('allowed only via POST')

class AddedFavoriteView(View):
     def get(self, request, *args, **kwargs):
        obj = Movie.objects.get(pk=kwargs['pk'])
        if obj not in request.user.mbuserprofile.favourites.all():
            request.user.mbuserprofile.favourites.add(obj)
            request.user.mbuserprofile.save()
            return render( request, 'favorite.html', {'response': 'The movie was added to your favorites list!'})
        else:
            request.user.mbuserprofile.favourites.remove(obj)
            request.user.mbuserprofile.save()
            return render( request, 'favorite.html', {'response': 'The movie was removed from your favorites list'})

MovieBoxProject/MovieBox/templates/actor.html
{% extends 'layout.html' %} 

{% block title %}MovieBox/{{ actor.first_name }} {{ actor.last_name }}{% endblock %} 

{% block content %}
<h1 style="color: #64993F;">{{ actor.first_name }} {{ actor.last_name}}</h1>
<div class="container well" style="background-color: #f6f2d9; border-color: #64993F; border-width: 2px; box-shadow: 2px 2px;">
<div class="pull-right">
  <img src="{{actor.picture.url}}" alt="pic" style="width: 200px">
</div>
<div>
    Date of birth: {{ actor.birth_date }}
</div>

<div>

    <h4 style="color: #64993F;">Played in:</h4>
      <ul>
       	{% for movie in actor.Movies.all %}
        <li><div style="display: inline-block;">
       		{{ movie.name }}
       		<a href="/movie/{{ movie.pk }}/">
                    <button class="btn btn-success">
                        Details
                    </button>
          </a>
          </div></li>

       {% endfor %}
  </ul>
</div>
</div>
{% endblock %}

MovieBoxProject/MovieBox/templates/add_actor.html
{% extends 'layout.html' %}

{% block title %}Add Actor{% endblock %}

{% block content %}

<h1 style="color: #64993F;"">Add actor</h1>

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{ form.errors }}
</div>
{% endif %}
<div class="container well" style="background-color: #f6f2d9; border-color: #64993F; border-width: 2px; box-shadow: 2px 2px;">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!--{{ form.as_p }}-->
   <div class="form-group">
        <label for="id_first_name">First name</label>
        <input class="form-control" id="id_first_name" type="text" name="first_name" value="{{ form.instance.first_name }}" maxlength="100" required/>
    </div>
    <div class="form-group">
        <label for="id_last_name">Last name</label>
        <input class="form-control" id="id_last_name" type="text" name="last_name" value="{{ form.instance.last_name }}" maxlength="100" required/>
    </div>
    <div class="form-group">
        <label for="id_birth_date">Birth date</label>
        <input class="form-control" id="id_birth_date" type="date" name="birth_date" value="{{ form.instance.birth_date }}" required>
    </div>
    <div>
        <label for="id_picture">Picture</label>
        <input id="id_picture" type="file" name="picture" required/>
    </div>
    <br>
    <button type="submit" class="btn btn-success">Add</button>
</form>

{% endblock %}

</div>

MovieBoxProject/MovieBox/templates/add_movie.html
<!DOCTYPE html>
{% extends 'layout.html' %}

{% block title %}Add Movie{% endblock %}

{% block content %}

<div class="container well" style="background-color: #f6f2d9; border-color: #64993F; border-width: 2px; box-shadow: 2px 2px;">
<h1 style="color: #64993F;">Add Movie</h1>

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{ form.errors }}
</div>
{% endif %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!--{{ form.as_p }}-->
    
    <div class="form-group">
        <label for="id_name">Name</label>
        <input class="form-control" id="id_name" type="text" name="name" value="{{ form.instance.name }}" maxlength="100" required/>
    </div>

    <div class="form-group">
        <label for="id_year">Date</label>
            <input class="form-control" id="id_year" type="date" name="date" value="{{ form.instance.date }}" required>
    </div>

    <div class="form-group">
        <label for="id_genre">Genre</label>
        <select id="id_genre" required name="genre" class="form-control">
              {% for value, display in form.fields.genre.choices %}
              <option value="{{ value }}"
                      {% if value == form.instance.genre %}
                            selected
                      {% endif %}>
                  {{ display }}
              </option>
              {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="id_actors">Actors</label>
        <select class="form-control" id="id_actors" name="actors" multiple>
            {% for actor in actors %}
                <option value="{{ actor.pk }}">
                    {{ actor.first_name|add:' '|add:actor.last_name }}
                </option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="id_description">Description</label>
        <textarea class="form-control" id="id_description" name="description" maxlength="5000" rows="10" cols="40" required>{{ form.instance.description }}</textarea>
    </div>
    <br/>
    <div>
        <label for="id_cover">Cover</label>
        <input id="id_cover" type="file" name="cover" required/>
    </div>
    <br/>
    <button type="submit" class="btn btn-success">Save</button>
</form>
</div>
{% endblock %}

MovieBoxProject/MovieBox/templates/edit_movie.html
<!DOCTYPE html>
{% extends 'layout.html' %}

{% block title %}Edit Movie{% endblock %}

{% block content %}

<div class="container well" style="background-color: #f6f2d9; border-color: #64993F; border-width: 2px; box-shadow: 2px 2px;">
<h1 style="color: #64993F;">Edit Movie</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!--{{ form.as_p }}-->
    <div class="form-group">
        <label for="id_name">Name</label>
        <input class="form-control" id="id_name" type="text" name="name" value="{{ form.instance.name }}" maxlength="100" required/>
    </div>
    <div class="form-group">
        <label for="id_date">Date</label>
        <input class="form-control" id="id_date" type="text" name="date" value="{{ form.instance.date|date:'d/m/Y' }}" required/>
    </div>
    <div class="form-group">
        <label for="id_genre">Genre</label>
        <select id="id_genre" required name="genre" class="form-control">
              {% for value, display in form.fields.genre.choices %}
              <option value="{{ value }}"
                      {% if value == form.instance.genre %}
                            selected
                      {% endif %}>
                  {{ display }}
              </option>
              {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="id_actors">Distribution</label>
        <select id="id_actors" name="actors" multiple  class="form-control">
            {% for actor in actors %}
                <option value="{{ actor.pk }}"
                    {% if movie_pk in actor.movies_pk %}
                        selected
                    {% endif %}
                >
                    {{ actor.first_name|add:' '|add:actor.last_name }}

                </option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="id_description">Description</label>
        <textarea  class="form-control" id="id_description" name="description" maxlength="5000" rows="10" cols="40" required>{{ form.instance.description }}</textarea>
    </div>
    <div style="display: inline-block;">
        <label for="id_cover">CoverPicture</label>
        <input id="id_cover" type="file" name="cover"/>
    </div>

    <br>
    <button type="submit" class="btn btn-success" style="padding: 15px; margin: 15px;">Save</button>
</form>

{% endblock %}

MovieBoxProject/MovieBox/templates/favorite.html
{% extends 'layout.html' %}

{% block title %}MovieBox{% endblock %}

{% block content %}
<h1> {{ response }} </h1>
{% endblock %}

MovieBoxProject/MovieBox/templates/form.html
<!DOCTYPE html>
{% extends 'layout.html' %}

{% block title %}Add/Edit movie{% endblock %}

{% block content %}

<h1>Add/Edit movie</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>

{% endblock %}

MovieBoxProject/MovieBox/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://bootswatch.com/3/cerulean/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
</head>

<body>
    {% include 'menu.html' %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.4/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    {% block scripts %}{% endblock %}
</body>

</html>

MovieBoxProject/MovieBox/templates/login.html
{% extends 'layout.html' %} {% block title %}Login{% endblock %} {% block content %}

<div class="container well" style="background-color: #f6f2d9; border-color: #64993F; border-width: 2px; box-shadow: 2px 2px;">
<h1 style="color: #64993F;">Login</h1>

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{ form.errors }}
</div>
{% endif %}


<form method="POST" enctype="multipart/formdata" class="form">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">Username:</label> 
        <input type="text" name="username" required="" id="id_username" class="form-control">
    </div>
    <div class="form-group">
        <label for="id_password">Password:</label> 
        <input type="password" name="password" required="" id="id_password" class="form-control">
    </div>
    <button type="submit" class="btn btn-success">Login</button>
</form>
</div>
{% endblock %}

MovieBoxProject/MovieBox/templates/menu.html
<nav >
    <script>
        function getSearchParams(){
            var input =  document.getElementById("searchBox").value;
            location.href="/search/" + input;
        }
    </script>
<nav class="navbar"  style="background-color: #f6f2d9;  border-color: #64993F; border-width: 2px; box-shadow: 2px 2px;"">
    <ul class="nav navbar-nav" >
    <li> {% load static %}<img src="{% static 'images/logo.jpg' %}" width = "200" ></li>
    <li style="margin-top: 20px"> <a href="{% url 'home' %}" style="color: black;">Home</a> </li>
    <li style="margin-top: 30px"> 
    <div class="input-group" style="margin-bottom: 5px; margin-top: -5px;">
    	<input type="text" placeholder="Search for a movie or an actor..." id="searchBox" class="form-control" style="width:70%;"> 
    	<button onclick="getSearchParams()" class="btn btn-default">Search</button>
    </div>
    </li>
     {% if not request.user.is_authenticated %}
     <li style="margin-top: 20px"><a href="{% url 'login' %}" style="color: black;">Login</a></li>
     <li style="margin-top: 20px"><a href="{% url 'register' %}" style="color: black;">Register</a></li>
     {% else %}
     <li style="margin-top: 20px"><a href="{% url 'movie_create' %}" style="color: black;">Add a new movie</a></li>
     <li style="margin-top: 20px"><a href="{% url 'actor_create' %}" style="color: black;">Add a new actor</a></li>
     <li style="margin-top: 20px"><a href="{% url 'profile' pk=user.mbuserprofile.pk %}" style="color: black;">Profile</a></li>
     <li style="margin-top: 20px"><a href="{% url 'logout' %}" style="color: black;">Logout</a></li>

     {% endif %}
    </ul>
    </nav>
</nav>

MovieBoxProject/MovieBox/templates/movie.html
{% extends 'layout.html' %}

{% block title %}MovieBox / {{ movie.name }}{% endblock %}

{% block content %}
<div class="container well" style="background-color: #f6f2d9; border-color: #64993F; border-width: 2px; box-shadow: 2px 2px;">
 <div style="float: right;">
            
			{% load static %}
		     {% if request.user.is_authenticated %}
			<a href="voted/1"><img src = "{% static 'images/star.png' %}" height = "30" width = "30"/></a>
			<a href="voted/2"><img src = "{% static 'images/star.png' %}" height = "30" width = "30"/></a>
			<a href="voted/3"><img src = "{% static 'images/star.png' %}" height = "30" width = "30"/></a>
			<a href="voted/4"><img src = "{% static 'images/star.png' %}" height = "30" width = "30"/></a>
			<a href="voted/5"><img src = "{% static 'images/star.png' %}" height = "30" width = "30"/></a>
			{% endif %}
			<br>
			<div style="float: right;">
			<h3 style="color: #64993F;">{{movie.score}}</h3>
		      </div>     
        </div>

    <div class="container">
    	<div style="text-align: center;">
        	<h2 style="color: #64993F;">{{movie.name}}</h2>

            {% if request.user.is_authenticated %}
            <a href="favorite/{{user.pk}}" style="color: #64993F;">
                {% if movie not in request.user.mbuserprofile.favourites.all %}Add to favorites{% else %}Remove from favorites{% endif %}
            </a>     
            {% endif %}
        </div>

      
            {{ movie.get_genre_display }}
            <br>
             {{movie.date}}
            <br>
            <div>
            	<img src="{{movie.cover.url}}" alt="pic" style="width: 200px">
            </div>

        </div>
        <br>
        <br>
        <br>
          <div class="container">
	        	{{movie.description}}
        </div>
        <div class="container">
    <h4 style="color: #64993F;">Cast</h4>
    <ul>
       {% for actor in movie.actors.all %}
            <li>
            	<div style="display:inline-block">{{ actor.first_name}} {{ actor.last_name}}
            	<a href="/actor/{{ actor.pk }}/">
                    <button class="btn btn-success">
                        Details
                    </button>
                </a>
                </div>

            </li>

        {% endfor %}
    </ul>
        </div>
          <div class="pull-left">

            {% if user.is_superuser %}
            <a href="/movie/{{ movie.pk }}/update"">
                 <button class="btn-success"  style="margin-top: 15px; padding:10px;">
                     Update
                 </button>
            </a>
            {% endif %}
            </div>
            

    </div>


{% endblock %}

MovieBoxProject/MovieBox/templates/profile.html
{% extends 'layout.html' %} 

{% block title %}Favorites{% endblock %} 

{% block content %}

<h1 style="color: #64993F;">{{ mbuserprofile.first_name }} {{ mbuserprofile.last_name}}' profile</h1>

<div class="container well" style="background-color: #f6f2d9; border-color: #64993F; border-width: 2px; box-shadow: 2px 2px;">
	 <div class="form-group">
	 	<h4 style="color: #64993F;">Email:</h4> {{ mbuserprofile.user.email }}
	 </div>
	<div>
		<h4 style="color: #64993F;">Birth day:</h4> {{ mbuserprofile.birth_date }}
	</div>

	<div class="container well" style="background-color: #f6f2d9; border-color: #64993F; border-width: 2px; box-shadow: 2px 2px; width: 90%">
	<h4 style="color: #64993F;">Favourites:</h4>
	{% for movie in mbuserprofile.favourites.all %}
		<p>{{ movie.name }}</p>
	{% endfor %}
	</div>

</div>

{% endblock %}

MovieBoxProject/MovieBox/templates/search.html
{% extends 'layout.html' %} 

{% block title %}MovieBox{% endblock %} 

{% block content %}

<h1 style="color: #64993F;"">Movies</h1>
{% for movie in items %}
<div class="container well" style="background-color: #f6f2d9; border-color: #64993F; border-width: 2px; box-shadow: 2px 2px;">
    <div style="float:left; padding: 30px">
        <img src="{{movie.cover.url}}" alt="pic" style="width: 200px">
    </div>
    <div>
        <h3 style="color: #64993F;">{{movie.name}}</h3>
        <div style="float: left;">
            Genre: {{ movie.get_genre_display }}
            <br>
             {{movie.date}}
            <br>
                <a href="/movie/{{ movie.pk }}/">
                    <button  class="btn-success"  style="margin-top: 15px; padding: 10px;">
                        Details
                    </button>
                </a>
            {% if user.is_superuser %}
            <a href="/movie/{{ movie.pk }}/update">
                 <button class="btn-success"  style="margin-top: 15px; padding:10px;">
                     Update
                 </button>
            </a>
            {% endif %}
        </div>
        <div style="float: right;">
            <h3 style="color: #64993F;">{{movie.score}}</h3>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

MovieBoxProject/MovieBox/templates/signup.html
{% extends 'layout.html' %} {% block title %}Sign Up{% endblock %} {% block content %}

<div class="container well" style="background-color: #f6f2d9; border-color: #64993F; border-width: 2px; box-shadow: 2px 2px;">
<h1 style="color: #64993F;">Sign Up</h1>

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{ form.errors }}
</div>
{% endif %}

<form method="POST" enctype="multipart/formdata" class="form">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">Username</label>
        <input id="id_username" type="text" name="email" value="{{ form.instance.email }}" maxlength="100" required class="form-control"/>
    </div>
    <div class="form-group">
        <label for="id_password">Password</label>
        <input id="id_password" type="password" name="password" value="{{ form.instance.password }}" required class="form-control"/>
    </div>
    <div class="form-group">
        <label for="id_password">Confirm Password</label>
        <input id="id_password" type="password" name="password" value="{{ form.instance.password }}" required class="form-control"/>
    </div>
    <div class="form-group">
        <label for="id_first_name">First Name</label>
        <input id="id_first_name" type="text" name="first_name" value="{{ form.instance.first_name }}" maxlength="200" required class="form-control"/>
    </div>
    <div class="form-group">
        <label for="id_last_name">Last Name</label>
        <input id="id_last_name" type="text" name="last_name" value="{{ form.instance.last_name }}" maxlength="200" required class="form-control"/>
    </div>
    <div class="form-group">
        <label for="id_birth_date">Birth Date</label>
        <input id="id_birth_name" type="date" name="birth_date" value="{{ form.instance.birth_date }}" required class="form-control"/>
    </div>
    <br/>
    <button type="submit" class="btn btn-success">Sign Up</button>
</form>
</div>
{% endblock %}

MovieBoxProject/MovieBox/templates/voted.html
{% extends 'layout.html' %}

{% block title %}MovieBox{% endblock %}

{% block content %}
<h1> {{ response }} </h1>
{% endblock %}